include: package:very_good_analysis/analysis_options.yaml

analyzer:
  exclude:
    - '**/*.freezed.dart'
    - '**/*.g.dart'
  errors:
    invalid_annotation_target: ignore

linter:
  rules:
    always_use_package_imports: true
    public_member_api_docs: false
    always_put_required_named_parameters_first: false
    use_if_null_to_convert_nulls_to_bools: false
    lines_longer_than_80_chars: false
    avoid_positional_boolean_parameters: false
